INSERT INTO druzyny (pozycja, nazwa_druzyny, tag_druzyny, kraj_pochodzenia)
VALUES  (1, 'Team Skała', 'TSK', 'Polska'),
	    (2, 'Reason Gaming', 'RSG', 'Polska'),
        (3, 'Team Misfits', 'MSF', 'Francja'),
        (4, 'eMonkeys', 'MKS', 'Hiszpania'),
        (5, 'Iluminar Gaming', 'IHG', 'Polska'),
        (6, 'Meet Your Makers', 'MYM', 'Hiszpania'),
        (7, 'SLKS Tramp Orneta', 'STO', 'Polska'),
        (8, 'JDS Gaming', 'JDS', 'Polska');
        
INSERT INTO zawodnicy (imie, nazwisko, nickname, kraj_pochodzenia, wiek, rola, druzyna)
VALUES ('Kajetan', 'Bąk', 'Arquel', 'Polska', 24, 'TOP', 'Team Skała'),
       ('Eugeniusz', 'Głowacki', 'Gucio', 'Polska', 23, 'JUNGLE', 'Team Skała'),
       ('Karol', 'Zawadzki', 'Overpow', 'Polska', 29, 'MID', 'Team Skała'),
       ('Aleks', 'Brzeziński', 'NZQ', 'Polska', 25, 'ADC', 'Team Skała'),
       ('Amadeusz', 'Wojciechowski', 'Delord', 'Polska', 27, 'SUPPORT', 'Team Skała'),
       ('Amadeusz', 'Krupa', 'Jokieez', 'Polska', 22, 'TOP', 'Reason Gaming'),
       ('Czesław', 'Przybylski', 'Xayoo', 'Polska', 23, 'JUNGLE', 'Reason Gaming'),
       ('Milan', 'Jankowski', 'TakeFun', 'Polska', 25, 'MID', 'Reason Gaming'),
       ('Łukasz', 'Chmielewski', 'Celaver', 'Polska', 21, 'ADC', 'Reason Gaming'),
       ('Józef', 'Sawicki', 'Libik', 'Polska', 22, 'SUPPORT', 'Reason Gaming'),
       ('Filip', 'Krawczyk', 'Melonik', 'Polska', 19, 'TOP', 'Iluminar Gaming'),
       ('Arkadiusz', 'Walczak', 'Tabasko', 'Polska', 26, 'JUNGLE', 'Iluminar Gaming'),
       ('Michał', 'Lis', 'Czajek', 'Polska', 21, 'MID', 'Iluminar Gaming'),
       ('Natan', 'Sikorski', 'Odi11',  'Polska', 19, 'ADC', 'Iluminar Gaming'),
       ('Amadeusz', 'Maciejewski', 'Czypsy', 'Polska', 20, 'SUPPORT', 'Iluminar Gaming'),
       ('Anastazy', 'Sikora', 'Śledziu', 'Polska', 36, 'TOP', 'SLKS Tramp Orneta'),
       ('Natan', 'Rutkowski', 'Junkos', 'Polska', 35, 'JUNGLE', 'SLKS Tramp Orneta'),
       ('Jarosław', 'Zieliński', 'NiQ', 'Polska', 40, 'MID', 'SLKS Tramp Orneta'),
       ('Rafał', 'Zalewski', 'Creaton', 'Polska', 39, 'ADC', 'SLKS Tramp Orneta'),
       ('Jerzy', 'Brzeziński', 'Veggie', 'Polska', 48, 'SUPPORT', 'SLKS Tramp Orneta'),
       ('Marcel', 'Szewczyk', 'LukiSteve', 'Polska', 22, 'TOP', 'JDS Gaming'),
       ('Józef', 'Górski', 'Popo', 'Polska', 21, 'JUNGLE', 'JDS Gaming'),
       ('Aleksander', 'Bąk', 'Vysotzky', 'Polska', 20, 'MID', 'JDS Gaming'),
       ('Gustaw', 'Wójcik', 'Dejvid', 'Polska', 18, 'ADC', 'JDS Gaming'),
       ('Antoni', 'Kamiński', 'Japczan', 'Polska', 23, 'SUPPORT', 'JDS Gaming'),
       ('Eryk', 'Andrzejewski', 'Kubon', 'Polska', 26, 'TOP', 'Meet Your Makers'),
       ('Tadeo', 'Mayonga', 'Razork', 'Hiszpania', 22, 'JUNGLE', 'Meet Your Makers'),
       ('Grham', 'Vallejo', 'xPeke', 'Hiszpania', 24, 'MID', 'Meet Your Makers'),
       ('Nevio', 'Prado', 'Flakked', 'Hiszpania', 20, 'ADC', 'Meet Your Makers'),
       ('Heinz', 'Villanueva', 'Irina', 'Hiszpania', 21, 'SUPPORT', 'Meet Your Makers'),
       ('Abram', 'Gallegos', 'Moryo', 'Hiszpania', 24, 'TOP', 'eMonkeys'),
       ('Renato', 'Alarcon', 'Akalos', 'Hiszpania', 25, 'JUNGLE', 'eMonkeys'),
       ('Cyrille', 'Collazo', 'Ocelote', 'Hiszpania', 27, 'MID', 'eMonkeys'),
       ('Melas', 'Henriquez', 'Kami', 'Hiszpania', 21, 'ADC', 'eMonkeys'),
       ('Adelio', 'Roybal', 'Vitekox', 'Hiszpania', 19, 'SUPPORT', 'eMonkeys'),
       ('Delmar', 'Guertin', 'Soaz', 'Francja', 27, 'TOP', 'Team Misfits'),
       ('Alexis', 'Morin', 'Adevine', 'Francja', 21, 'JUNGLE', 'Team Misfits'),
       ('Adrien', 'Souplet', 'Vetheo', 'Francja', 20, 'MID', 'Team Misfits'),
       ('Mercer', 'Grimard', 'Hans Sama', 'Francja', 20, 'ADC', 'Team Misfits'),
       ('Tearlach', 'Brisette', 'YellowStar', 'Francja', 26, 'SUPPORT', 'Team Misfits');
       
INSERT INTO komentatorzy (imie, nazwisko, nickname)
VALUES  ('Kamil', 'Zieliński', 'Myha'),
	('Olaf', 'Tomaszewski', 'Silvan'),
        ('Anastazy', 'Mazurek', 'Avahir'),
        ('Tomasz', 'Mazur', 'TheFakeOne'); 
        
INSERT INTO harmonogram (druzyna_niebieska, druzyna_czerwona, data_spotkania, godzina_spotkania, id_komentatora)
VALUES  ('Team Skała', 'Reason Gaming', '2021-01-08', '17:00:0', 4),
	('SLKS Tramp Orneta', 'eMonkeys', '2021-01-08', '18:00:0', 1),
        ('Meet Your Makers', 'JDS Gaming', '2021-01-08', '19:00:0', 2),
        ('Iluminar Gaming', 'Team Misfits', '2021-01-08', '20:00:0', 3),
        ('Team Skała', 'Team Misfits', '2021-01-09', '17:00:0', 1),
        ('Reason Gaming', 'Iluminar Gaming', '2021-01-09', '18:00:0', 2),
        ('SLKS Tramp Orneta', 'JDS Gaming', '2021-01-09', '19:00:0', 3), 
        ('eMonkeys', 'Meet Your Makers', '2021-01-09', '20:00:0', 4),
        ('Team Skała', 'SLKS Tramp Orneta', '2021-01-15', '17:00:0', 3),
        ('Reason Gaming', 'eMonkeys', '2021-01-15', '18:00:0', 2),
        ('Meet Your Makers', 'Iluminar Gaming', '2021-01-15', '19:00:0', 4),
        ('JDS Gaming', 'Team Misfits', '2021-01-15', '20:00:0', 1),
        ('Team Skała', 'eMonkeys', '2021-01-16', '17:00:0', 2),
        ('Reason Gaming', 'SLKS Tramp Orneta', '2021-01-16', '18:00:0', 4),
        ('Meet Your Makers', 'Team Misfits', '2021-01-16', '19:00:0', 1),
        ('JDS Gaming', 'Iluminar Gaming', '2021-01-16', '20:00:0', 3),
        ('Team Skała', 'Meet Your Makers', '2021-01-22', '17:00:0', 4),
        ('Reason Gaming', 'JDS Gaming', '2021-01-22', '18:00:0', 2),
        ('SLKS Tramp Orneta', 'Iluminar Gaming', '2021-01-22', '19:00:0', 3),
        ('eMonkeys', 'Team Misfits', '2021-01-22', '20:00:0', 1),
        ('Team Skała', 'JDS Gaming', '2021-01-23', '17:00:0', 2),
        ('Reason Gaming', 'Meet Your Makers', '2021-01-23', '18:00:0', 4),
        ('SLKS Tramp Orneta', 'Team Misfits', '2021-01-23', '19:00:0', 1),
        ('eMonkeys', 'Iluminar Gaming', '2021-01-23', '20:00:0', 3),
        ('Team Skała', 'Iluminar Gaming', '2021-01-29', '17:00:0', 1),
        ('Reason Gaming', 'Team Misfits', '2021-01-29', '18:00:0', 4), 
        ('SLKS Tramp Orneta', 'Meet Your Makers', '2021-01-29', '19:00:0', 3),
        ('eMonkeys', 'JDS Gaming', '2021-01-29', '20:00:0', 2);
        
INSERT INTO kary (rodzaj_kary, powod, konsekwencja, id_zawodnika)
VALUES ('Grzywna', 'Obstawianie meczy swojej drużyny w totalizatorze sportowym (kara za poprzedni sezon)', '5000zł', 2),
       ('Grzywna', 'Obstawianie meczy swojej drużyny w totalizatorze sportowym (kara za poprzedni sezon)', '5000zł', 5),
       ('Grzywna', 'Brak stawienia się na prezentaccji drużyn', '500zł', 36),
       ('Grzywna', 'Brak stawienia się na prezentaccji drużyn', '500zł', 37),
       ('Grzywna', 'Brak stawienia się na prezentaccji drużyn', '500zł', 38),
       ('Grzywna', 'Brak stawienia się na prezentaccji drużyn', '500zł', 39),
       ('Grzywna', 'Brak stawienia się na prezentaccji drużyn', '500zł', 40),
       ('Zawieszenie', 'Obrażanie innych zawodników i/lub drużyn podczas swojej transmisji na żywo', 'Zawieszenie na dwa kolejne mecze ligowe', 2),
       ('Grzywna', 'Niestawienie się na mecz swojej drużyny (kara za poprzedni sezon)', '1000zł', 20),
       ('Grzywna', 'Niestawienie się na mecz swojej drużyny (kara za poprzedni sezon)', '1000zł', 16),
       ('Grzywna', 'Niestawienie się na mecz swojej drużyny (kara za poprzedni sezon)', '1000zł', 33),
       ('Zawieszenie', 'Obrażanie innych zawodników i/lub druzyn podczas swojej transmisji na żywo', 'Zawieszenie na dwa kolejne mecze ligowe', 7),
       ('Zawieszenie', 'Obrażanie innych zawodników i/lub druzyn podczas swojej transmisji na żywo', 'Zawieszenie na dwa kolejne mecze ligowe', 8),
       ('Zawieszenie', 'Obrażanie innych zawodników i/lub druzyn podczas swojej transmisji na żywo', 'Zawieszenie na dwa kolejne mecze ligowe', 37),
       ('Grzywna', 'Niestawienie się na mecz swojej drużyny (kara za poprzedni sezon)', '1000zł', 2);
               
        
        